OTC-838: restricted managing regions and districts
openimis/openimis-fe-location_js pull request #42
Opened 2023-02-20 16:10 UTC by lruzicki

TIcket:
https://openimis.atlassian.net/browse/OTC-838

Related PR:
https://github.com/openimis/openimis-be-location_py/pull/53

2023-02-24 10:46 UTC, olewandowski1 commented on src/components/TypeLocationsPaper.js
> +      this.props?.rights.includes(RIGHT_REGION_LOCATION_ADD)
There is no need to use _Boolean()_, because _.includes()_ is returning boolean value by default.

2023-02-24 10:46 UTC, olewandowski1 commented on src/pages/LocationsPage.js
> +      this.props?.rights.includes(RIGHT_REGION_LOCATION_ADD)
There is no need to use _Boolean()_, because _.includes()_ is returning boolean value by default.

2023-02-24 10:51 UTC, olewandowski1 commented on src/components/TypeLocationsPaper.js
>      const { classes, rights, title, onRefresh, onEdit, readOnly, location, ...others } = this.props;
This line seems to be a little bit too long. Consider to restructure it to the same shape as the import in 14th line.

2023-02-24 10:52 UTC, olewandowski1 commented on src/pages/LocationsPage.js
>  import { fetchLocations, clearLocations, createOrUpdateLocation, deleteLocation, moveLocation } from "../actions";
This line seems to be a little bit too long. Consider to restructure it.

2023-02-24 10:52 UTC, olewandowski1 commented on src/pages/LocationsPage.js
>  import { Helmet, withModulesManager, formatMessageWithValues, journalize, formatMessage } from "@openimis/fe-core";
This line seems to be a little bit too long. Consider to restructure it.

2023-02-24 10:53 UTC, olewandowski1 requested changes
I left you some comments @lruzicki , please refer to them.

2023-02-27 14:04 UTC, olewandowski1 commented on src/pages/LocationsPage.js
> +              type={3} createRegionLocationRight
This  probably _createRegionLocationRight_ should not be here.

2023-02-28 15:08 UTC, dborowiecki requested changes

2023-02-28 15:08 UTC, dborowiecki commented on src/pages/LocationsPage.js
> +                  onDelete={createRegionLocationRight ? (l, idx) => this.onDelete(l, idx, 0) : null}
Should createRegion be also used to do the check on delete action? Perhaps we should introduce separate variables for all actions or change name from createRegionLocationRight to manageRegionLocationRight?

2023-02-28 15:08 UTC, dborowiecki commented on src/pages/LocationsPage.js
> +  rights: !!state.core && !!state.core.user && !!state.core.user.i_user ? state.core.user.i_user.rights : [],
```suggestion
  rights:state?.core?.user?.i_user?.rights || [],
```
should work as well

2023-03-02 11:30 UTC, dborowiecki approved these changes

2023-03-02 11:36 UTC, olewandowski1 approved these changes
LGTM

2023-03-02 11:42 UTC, merged